adding "grab n slide" Musette into marble
metmuseum/marble pull request #180
Opened 2022-03-10 22:00 UTC by davidseguin

2022-03-10 22:24 UTC, stephenhmarsh requested changes

2022-03-10 22:24 UTC, stephenhmarsh commented on dist/marble.js.LICENSE.txt
> +/*! ../../../global/settings */
I'm not sure what all this cruft is? 🤔  Could you just delete this file and rebuild dist?

2022-03-10 22:24 UTC, stephenhmarsh commented on dist/marble.js
> +(()=>{var e={"./node_modules/@vimeo/player/dist/player.es.js":(e,t,s)=>{"use strict";function n(e,t){if(!(e instanceof t))throw new TypeError("Cannot call a class as a function")}function o(e,t){for(
Hm, not sure how but looks like a broken build?

2022-03-10 22:24 UTC, stephenhmarsh commented on package-lock.json
> +				"agent-base",
looks like maybe you had a bad merge?

2022-03-10 22:24 UTC, stephenhmarsh commented on src/components/musette/musette.stories.js
> +export default { title: "Carousel/Musette", decorators: [withKnobs] };
the knobs addon has been buggy. better to just remove it, especially if you don't have any.  we're now slowly migrating to controls/args.

2022-03-10 22:24 UTC, stephenhmarsh commented on src/components/musette/musette.stories.js
> +				<img src="https://collectionapi.metmuseum.org/api/collection/v1/iiif/503578/1358034/main-image">
probably better if you can change the `src` for all of these to one of our storybook image helpers, so we're not depending on non-local assets in test environments for snapshots. not a blocker but its preferred.

2022-03-10 22:24 UTC, stephenhmarsh commented on src/components/musette/musette.js
> +		const getMusetteSpecs = (laMusette) => {
i think @JosephCurley wanted to use https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API ?

2022-03-10 22:24 UTC, stephenhmarsh commented on src/components/musette/musette.js
> +		laMusette.addEventListener("scroll", () => {
should we throttle or debounce this, for performance?

2022-03-10 22:24 UTC, stephenhmarsh commented on src/components/musette/musette.js
> +				for(let i = 0; i<musettteLinks.length; i++) {
refactor to `.forEach` ?

2022-03-10 22:42 UTC, stephenhmarsh commented on src/components/musette/musette.scss
> +	background: no-repeat center/20px url("https://www.metmuseum.org/Rodan/dist/svg/banner-link-back.svg");
I think we shouldn't depend on a file in Rodan here. Probably best to inline it as a data-uri svg. ? What do you think @JosephCurley

2022-03-30 16:58 UTC, JosephCurley approved these changes
This is looking good - I can imagine a few places to take it, but Im cool with merging it in whenever

2022-06-02 20:52 UTC, stephenhmarsh approved these changes
great job, thanks @davidseguin

2022-06-03 15:35 UTC, merged