DIGCOLL-5750 New basic "Jump To..." banner
metmuseum/marble pull request #213
Opened 2022-12-09 18:26 UTC by davidseguin

This will be the first component in an updated banner. Details here: https://jira.metmuseum.org/browse/DIGCOLL-5750

2022-12-09 18:40 UTC, stephenhmarsh commented
Worth mentioning: Our focus states on links are just a thin underline, not really accessible at all, but that's not the fault of this branch. 

<img width="744" alt="Screenshot 2022-12-09 at 1 38 16 PM" src="https://user-images.githubusercontent.com/6576730/206770227-baa142cd-0290-4ec6-8b42-234099e4f6e5.png">

2022-12-09 18:46 UTC, stephenhmarsh requested changes
nice but just have a few comments, thanks (:

2022-12-09 18:46 UTC, stephenhmarsh commented on src/components/jump-to-banner/jump-to-banner.js
> +			const handleLinkClick = (jumpToLink) => {
hm, i don't see any _need_ for this handler to be defined here?  if you could move it out of this function to the top level and just reference it, that would cut down on this function being 27 lines long.

2022-12-09 18:46 UTC, stephenhmarsh commented on src/components/jump-to-banner/jump-to-banner.js
> +			let jumpToLinks = jumpToBanner.querySelectorAll(".js-jump-to__link");
nitpick: this value doesn't change, so i think `const` is more appropriate

2022-12-09 18:46 UTC, stephenhmarsh commented on src/components/jump-to-banner/jump-to-banner.js
> +		jumpToBanners.forEach((jumpToBanner)=> {
do we need to iterate through the _banners_? if you think about it, all the logic is nicely scoped to the individual link.  you could just iterate through those without this forEach.

2022-12-09 18:54 UTC, stephenhmarsh commented on src/components/jump-to-banner/jump-to-banner.js
> +				window.scrollTo({
you might want to consider https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView which I think would respect CSS scroll-margin

2022-12-09 21:39 UTC, stephenhmarsh approved these changes

2022-12-13 20:14 UTC, JosephCurley approved these changes

2022-12-19 20:08 UTC, merged